/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogicaDePresentacion;

import Estructuras.*;
import javax.swing.JOptionPane;

/**
 *Pantalla de configuración inicial 
 */
public class Configuracion extends javax.swing.JFrame {

    /**
     * Metodo para la configuracion de la GUI 
     */
    public Configuracion() {
        initComponents();
        grupoEntregas.add(colaEntregas);
        grupoEntregas.add(heapEntregas);
        grupoSeguridad.add(colaSeguridad);
        grupoSeguridad.add(heapSeguridad);        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEntregas = new javax.swing.ButtonGroup();
        grupoSeguridad = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        colaEntregas = new javax.swing.JRadioButton();
        heapEntregas = new javax.swing.JRadioButton();
        colaSeguridad = new javax.swing.JRadioButton();
        heapSeguridad = new javax.swing.JRadioButton();
        cantidadEntregas = new javax.swing.JTextField();
        cantidadSeguridad = new javax.swing.JTextField();
        minimoSeguridad = new javax.swing.JTextField();
        maximoSeguridad = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Configuración CourierTEC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 39));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad de ventanillas entregas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de ventanillas seguridad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manejo de seguridad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manejo de entregas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tiempo minímo de espera:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tiempo máximo de espera:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 102, 0));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 119, -1));

        btnIniciar.setBackground(new java.awt.Color(0, 102, 0));
        btnIniciar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 111, -1));

        colaEntregas.setForeground(new java.awt.Color(255, 255, 255));
        colaEntregas.setText("Cola de prioridad");
        getContentPane().add(colaEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 120, -1));

        heapEntregas.setForeground(new java.awt.Color(255, 255, 255));
        heapEntregas.setText("Heap");
        getContentPane().add(heapEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 60, -1));

        colaSeguridad.setForeground(new java.awt.Color(255, 255, 255));
        colaSeguridad.setText("Cola de prioridad");
        getContentPane().add(colaSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 120, -1));

        heapSeguridad.setForeground(new java.awt.Color(255, 255, 255));
        heapSeguridad.setText("Heap");
        getContentPane().add(heapSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 60, -1));
        getContentPane().add(cantidadEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 180, -1));
        getContentPane().add(cantidadSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 180, -1));
        getContentPane().add(minimoSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 180, -1));
        getContentPane().add(maximoSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 180, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo1.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        // TODO add your handling code here:
        try{                                
            int cantidadC=Integer.parseInt(cantidadEntregas.getText());
            int cantidadS=Integer.parseInt(cantidadSeguridad.getText());
            String estructuraCheckin;
            String estructuraSeguridad;
            
            if (colaEntregas.isSelected()==true){
                estructuraCheckin="cola";
            }else if(heapEntregas.isSelected()==true){
                estructuraCheckin= "heap";
            }else{
                JOptionPane.showMessageDialog(this, "Por favor, escoger una estructura para la ventanilla de seguridad");
                return;
            }
            if(colaSeguridad.isSelected()==true){
                estructuraSeguridad= "cola"; 
            }else if(heapSeguridad.isSelected()==true){
                estructuraSeguridad= "heap";
            }else{
                JOptionPane.showMessageDialog(this, "Por favor, escoger una estructura para la ventanilla de seguridad");
                return;                
            }            
            //Integer.parseInt convierte el texto de las cajas en números enteros               
            new Principal(cantidadC, estructuraCheckin, cantidadS, estructuraSeguridad,
                    Integer.parseInt(minimoSeguridad.getText()), Integer.parseInt(maximoSeguridad.getText())).setVisible(true);
        }
        catch(Exception errorDeLlenado){
            System.out.println(errorDeLlenado);
        }
        dispose();
    }//GEN-LAST:event_btnIniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JTextField cantidadEntregas;
    private javax.swing.JTextField cantidadSeguridad;
    private javax.swing.JRadioButton colaEntregas;
    private javax.swing.JRadioButton colaSeguridad;
    private javax.swing.ButtonGroup grupoEntregas;
    private javax.swing.ButtonGroup grupoSeguridad;
    private javax.swing.JRadioButton heapEntregas;
    private javax.swing.JRadioButton heapSeguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField maximoSeguridad;
    private javax.swing.JTextField minimoSeguridad;
    // End of variables declaration//GEN-END:variables
}
